fix: runit-init - apt-get compatibility
 - added invoke-rc.d.runit for service startup-removal from dpkg.
   This fixes the issue with deleted sv binary when symlinked to /etc/init.d/
   while running 'apt-get purge SERVICE'.
 - fix: svactivate/svdeactivate verbosity
 - fix: update-rc.d - do not require /etc/insserv.conf to use insserv

diff --git a/modules/runit-init/inst/svactivate b/modules/runit-init/inst/svactivate
--- a/modules/runit-init/inst/svactivate
+++ b/modules/runit-init/inst/svactivate
@@ -3,6 +3,9 @@
 # runit service activation
 # (cloux@rote.ch)
 
+# We need to be root
+if [ $(id -u) -ne 0 ]; then printf '%s: Need to be root!\n' "$0"; exit 1; fi
+
 if [ $# -eq 0 ]; then
 	printf 'Enter Runit service names as a parameter.\n'
 	printf 'Supported services are listed in /etc/sv/\n'
@@ -14,18 +17,18 @@ RET=0
 for SRV in "$@"; do
 	SRVNAME=${SRV##*/}
 	if [ -d "/etc/service/$SRVNAME" ]; then
-		printf 'Runit service '%s' is already active, starting it...\n' "$SRVNAME"
+		printf 'Runit service "%s" is already active, starting it...\n' "$SRVNAME"
 		sv up $SRVNAME
 		continue
 	fi
 	if [ ! -d "/etc/sv/$SRVNAME" ]; then
-		printf 'ERROR: Runit service definition '/etc/sv/%s' not found, activation failed\n' "$SRVNAME"
+		printf 'ERROR: Runit service definition "/etc/sv/%s" not found, activation failed\n' "$SRVNAME"
 		RET=1
 		continue
 	fi
 	ln -s "/etc/sv/$SRVNAME" /etc/service/ 2>/dev/null
 	if [ $? -ne 0 ]; then
-		printf 'ERROR: Runit service '%s' activation failed\n' "$SRVNAME"
+		printf 'ERROR: Runit service "%s" activation failed\n' "$SRVNAME"
 		RET=1
 		continue
 	fi
