fix: adoptopenjdk
 - fix: error 403 during download, caused by weird AWS S3 bucket behavior.
   Added "referrer" header and fake "user-agent" to wget to solve this.
 - fix: handling of alternatives during reinstallations
 - fix: verbosity
 - add: maintain "default-java" symlink required by some apps
 - add: automatically handle dangling invalid alternative links
 - add: cleanup to remove all installed JDK alternatives except default

diff --git a/modules/adoptopenjdk/install b/modules/adoptopenjdk/install
--- a/modules/adoptopenjdk/install
+++ b/modules/adoptopenjdk/install
@@ -44,7 +44,7 @@ else
 	MAN_PATH=~/.local/share/man
 	# add local manpages to ~/.manpath
 	MANPATH_LINE="MANDATORY_MANPATH $MAN_PATH"
-	grep -qF "$MANPATH_LINE" ~/.manpath 2>/dev/null || \
+	grep -qF "$MANPATH_LINE" ~/.manpath 2>/dev/null ||
 	  printf '%s\n' "$MANPATH_LINE" >> ~/.manpath
 fi
 
@@ -83,66 +83,70 @@ BIN_FILE=$(printf '%s' "$BIN_LINK" | grep -o '[^/]*$')
 # download the file if necessary
 [ -d "$ARCHIVE_DIR" ] || mkdir -p "$ARCHIVE_DIR"
 cd $ARCHIVE_DIR || exit 1
-if [ -f "$BIN_FILE" ] && [ "$BIN_SIZE" -eq "$(stat -c '%s' "$BIN_FILE")" ]; then
+if [ -f "$BIN_FILE" ] && [ "$BIN_SIZE" -ge "$(stat -c '%s' "$BIN_FILE")" ]; then
 	printf 'Package already available: %s/%s\n' "$ARCHIVE_DIR" "$BIN_FILE"
 	gzip --test "$BIN_FILE" || rm -f "$BIN_FILE"
 fi
 if [ ! -f "$BIN_FILE" ]; then
 	printf 'Downloading into %s ...\n\n' "$ARCHIVE_DIR"
-	wget -4 --progress=dot:giga "$BIN_LINK" || exit 1
+	wget -U 'Mozilla/5.0 (X11; Linux i686; rv:64.0) Gecko/20100101 Firefox/64.0' \
+	--referer="$API_ASSETS" -4 --progress=dot:giga "$BIN_LINK" || exit 1
 fi
 [ -s "$BIN_FILE" ] || exit 1
-
-# delete old distributions from cache
-find "$ARCHIVE_DIR" -maxdepth 1 -type f -iname '*'${BIN_TYPE}_${ARCH}_${OS}_${JVM}'*' \
- ! -iname "$BIN_FILE" -delete
 
 # unpack
 printf 'Unpacking %s ... ' "$BIN_FILE"
 tar xzf "$BIN_FILE"
 if [ $? -ne 0 ]; then
 	printf 'ERROR\n'
+	rm -vf "$BIN_FILE"
 	exit 1
 fi
 printf 'OK\n'
 ADOPT_DIR=$(find -maxdepth 1 -type d -iname '*'$BIN_TYPE'*' -printf '%f' -quit)
 
-# check if already installed
-if [ -d "$TARGET_PATH/$ADOPT_DIR" ]; then
-	printf '\n%s is already installed in %s.\n' "$ADOPT_DIR" "$TARGET_PATH"
-	rm -rf "$ADOPT_DIR"
-	exit
-fi
+# delete old distributions from cache
+find "$ARCHIVE_DIR" -maxdepth 1 -type f ! -iname "$BIN_FILE" \
+  -iname '*'${BIN_TYPE}_${ARCH}_${OS}_${JVM}_${VERSION}'*' -delete
 
 # install
-printf 'Installing into %s ...\n' "$TARGET_PATH/$ADOPT_DIR"
-[ -d "$TARGET_PATH" ] || mkdir -p "$TARGET_PATH"
-mv -t "$TARGET_PATH" "$ADOPT_DIR"
+if [ -d "$TARGET_PATH/$ADOPT_DIR" ]; then
+	printf 'Path %s already exists.\n' "$TARGET_PATH/$ADOPT_DIR"
+	rm -rf "$ADOPT_DIR"
+else
+	printf 'Installing into %s ...\n' "$TARGET_PATH/$ADOPT_DIR"
+	[ -d "$TARGET_PATH" ] || mkdir -p "$TARGET_PATH"
+	mv -t "$TARGET_PATH" "$ADOPT_DIR"
+	chown -R root: "$TARGET_PATH/$ADOPT_DIR"
+fi
 cd "$TARGET_PATH"/"$ADOPT_DIR" || exit 1
-rm -f "$TARGET_PATH/latest"
-ln -sf "$ADOPT_DIR" "$TARGET_PATH/latest"
+rm -f "$TARGET_PATH/latest" 2>/dev/null && ln -sf "$ADOPT_DIR" "$TARGET_PATH/latest"
+rm -f "$TARGET_PATH/default-java" 2>/dev/null && ln -sf latest "$TARGET_PATH/default-java"
 
 # install manpages
+# NOTE: this ignores the update-alternatives system!
 printf 'Installing manpages ... '
 find man -type f ! -iname '*.gz' -exec gzip '{}' \;
 [ -d "$MAN_PATH"/man1 ] || mkdir -p "$MAN_PATH"/man1
-# NOTE: this ignores the update-alternatives system! 
 ln -sf -t "$MAN_PATH"/man1 "$TARGET_PATH"/latest/man/man1/*.gz
 printf 'OK\n'
 
 # update-alternatives for system installation
-if [ $(id -u) -eq 0 ]; then
-	if [ "$(command -v update-alternatives)" ]; then
-		printf 'Updating alternatives ...\n'
-		for f in $(find "$TARGET_PATH/$ADOPT_DIR/bin" -type f -printf '%f '); do
-			update-alternatives --install /usr/bin/$f $f "$TARGET_PATH/$ADOPT_DIR/bin/$f" 400
-			update-alternatives --set $f "$TARGET_PATH/$ADOPT_DIR/bin/$f"
+ALT=$(command -v update-alternatives || command -v alternatives)
+if [ $(id -u) -eq 0 ] && [ -x "$ALT" ]; then
+	for f in $(find "$TARGET_PATH/$ADOPT_DIR/bin" -type f -printf '%f '); do
+		if ! $ALT --display $f 2>/dev/null | grep currently | grep -q "$ADOPT_DIR"; then
+			printf 'Set alternative for %s to %s\n' "$f" "$ADOPT_DIR"
+			$ALT --install /usr/bin/$f $f "$TARGET_PATH/$ADOPT_DIR/bin/$f" 400 >/dev/null 2>/dev/null
+			$ALT --set $f "$TARGET_PATH/$ADOPT_DIR/bin/$f" >/dev/null 2>/dev/null
+		fi
+		for invalid in $($ALT --display $f 2>&1 | grep warning: | grep -o '/.*/'); do
+			printf 'Remove invalid alternative %s\n' "$invalid$f"
+			$ALT --remove $f "$invalid$f" >/dev/null 2>/dev/null
 		done
-	else
-		printf '\nAdd "%s" into your PATH.\n\n' "$TARGET_PATH/latest/bin"
-	fi
+	done
 else
 	printf '\nAdd "%s" into your PATH.\n\n' "$TARGET_PATH/latest/bin"
 fi
 
-printf 'Installation complete.\n\n'
+printf '\nDONE\n\n'
