fix: minikube, kubectl
 - fix: kubectl formatting
 - fix: minikube - formatting, latest version check
 - add: minikube - completions

diff --git a/modules/minikube/install b/modules/minikube/install
--- a/modules/minikube/install
+++ b/modules/minikube/install
@@ -3,7 +3,7 @@
 #
 # (cloux@rote.ch)
 
-printf "Install minikube\n\n"
+printf 'Install minikube\n\n'
 
 if [ $(id -u) -ne 0 ]; then printf 'Need to be root!\n'; exit 1; fi
 
@@ -17,35 +17,44 @@ done
 
 # check versions
 if [ "$(command -v minikube)" ]; then
-	CURRENT=$(minikube version | grep version | grep -o '[^ ]*$')
-	printf 'Current version: %s\n' "$CURRENT" 
+	INST_VERSION=$(minikube version 2>/dev/null | grep version | grep -o '[0-9.]*$')
+	printf 'Installed version: %s\n' "$INST_VERSION"
 fi
-printf ' Latest version: '
+printf '   Latest version: '
+JSON_FILE=$(mktemp)
 LATEST_STABLE_LINK="https://api.github.com/repos/kubernetes/minikube/releases/latest"
-LATEST=$(wget -q "$LATEST_STABLE_LINK" -O - 2>/dev/null | jq -r '.name')
-if [ -z "$LATEST" ]; then
-	printf "ERROR: latest version check failed.\n"
+wget -q "$LATEST_STABLE_LINK" -O "$JSON_FILE" 2>/dev/null
+LATEST_VERSION=$(jq -r '.name' "$JSON_FILE" | grep -o '[0-9.]*')
+LATEST_LINK=$(jq -r '.assets[].browser_download_url' "$JSON_FILE" | grep -i $(uname -s))
+rm "$JSON_FILE"
+if [ -z "$LATEST_VERSION" ]; then
+	printf 'ERROR: latest version check failed.\n'
 	exit
 fi
-printf '%s\n\n' "$LATEST"
-if [ "$CURRENT" = "$LATEST" ]; then
+printf '%s\n\n' "$LATEST_VERSION"
+if [ "$INST_VERSION" ] && [ "$LATEST_VERSION" = "$INST_VERSION" ]; then
 	printf 'Up to date, nothing to do.\n'
 	exit
 fi
 
 # download
 cd /tmp || exit 1
-
 MINIKUBE_LINK="https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"
 wget -4 -N -nd --progress=dot:giga "$MINIKUBE_LINK"
-if [ $? -ne 0 ] || [ ! -s $FILENAME ]; then
-	printf "ERROR: download failed.\n"
+if [ $? -ne 0 ] || [ ! -s minikube-linux-amd64 ]; then
+	printf 'ERROR: download failed.\n'
 	exit
 fi
 
 # install
 printf 'Installing to /usr/local/bin/ ...\n'
-chmod 755 kubectl
-mv -f -t /usr/local/bin/ kubectl || exit 1
+chmod 755 minikube-linux-amd64
+mv -f minikube-linux-amd64 /usr/local/bin/minikube || exit 1
+
+# shell completions
+[ -d /usr/share/bash-completion/completions ] &&
+	minikube completion bash 2>/dev/null > /usr/share/bash-completion/completions/minikube
+[ -d /usr/share/zsh/site-functions ] &&
+	minikube completion zsh 2>/dev/null > /usr/share/zsh/site-functions/_minikube
 
 printf '\nDONE\n'
