fix: gitahead - use github API JSON instead of website parsing

diff --git a/modules/gitahead/install b/modules/gitahead/install
--- a/modules/gitahead/install
+++ b/modules/gitahead/install
@@ -7,30 +7,39 @@
 
 if [ $(id -u) -ne 0 ]; then printf 'Need to be root!\n'; exit 1; fi
 
+# check dependencies
+for DEP in wget jq; do
+	if ! command -v "$DEP" >/dev/null; then
+		printf 'ERROR: Please install "%s" to continue.\n' "$DEP"
+		exit 1
+	fi
+done
+
+# check version
 if [ -x /opt/GitAhead/GitAhead ]; then
 	INST_VERSION=$(/opt/GitAhead/GitAhead --version 2>/dev/null | grep -o '[0-9][0-9.]*[0-9]')
 	printf ' Instaled version: %s\n' "$INST_VERSION"
 fi
-
 printf '   Latest version: '
-LATEST_LINK="https://github.com/gitahead/"$(wget -q4 -O - \
-https://github.com/gitahead/gitahead/releases/latest | grep -o 'gitahead/releases/download/[^"]*\.sh')
-LATEST_FILE=$(printf '%s' "$LATEST_LINK" | grep -o '[^/]*$')
-if [ -z "$LATEST_FILE" ]; then
-	printf 'unknown.\n\n'
-	printf 'Check manualy at https://github.com/gitahead/gitahead/releases/latest\n\n'
-	exit 1
-fi
-LATEST_VERSION=$(printf '%s' "$LATEST_FILE" | grep -o '[0-9][0-9.]*[0-9]')
-printf '%s\n' "$LATEST_VERSION"
-if [ "$INST_VERSION" ] && [ "$LATEST_VERSION" = "$INST_VERSION" ]; then
-	printf '\nGitAhead is up to date.\n\n'
+JSON_FILE=$(mktemp)
+wget -q "https://api.github.com/repos/gitahead/gitahead/releases/latest" -O "$JSON_FILE" 2>/dev/null
+LATEST_VERSION=$(jq -r '.name' "$JSON_FILE" | grep -o '[^a-z]*')
+LATEST_LINK=$(jq -r '.assets | map(select(.content_type == "application/x-sh"))[0] | .browser_download_url' "$JSON_FILE")
+rm "$JSON_FILE"
+if [ -z "$LATEST_VERSION" ]; then
+	printf "ERROR: latest version check failed.\n"
 	exit
 fi
-printf '\n'
+printf '%s\n\n' "$LATEST_VERSION"
+if [ "$INST_VERSION" ] && [ "$LATEST_VERSION" = "$INST_VERSION" ]; then
+	printf 'GitAhead is up to date.\n'
+	exit
+fi
 
+# install
 cd /opt
 wget -4 -r -nd -nc --progress=dot:giga $LATEST_LINK || exit 1
+LATEST_FILE=$(printf '%s' "$LATEST_LINK" | grep -o '[^/]*$')
 [ -s "$LATEST_FILE" ] || exit 1
 
 chmod 755 "$LATEST_FILE"
